### ISSUE TITLE
Error reading trx file

### ISSUE THREAD

**Issue by brunosmm** [bibipkins/dotnet-test-reporter#43]
Hello, 

First thanks for the actions, seems would help us a lot get visibility on the PRs.
Once we ran with the files in attach we got this error below, but we have no visibility why and what is the error, can you help on this?

<img width="792" alt="image" src="https://github.com/bibipkins/dotnet-test-reporter/assets/1554850/8c895c3a-4a75-4200-adad-994ff3ccaed8">

Cheers
[dotnet-results.zip](https://github.com/bibipkins/dotnet-test-reporter/files/13469399/dotnet-results.zip)

**Comment by bibipkins** [comment]
@brunosmm Sorry for taking so long to respond! If you are still interested bug with trx parsing has already been reported and fixed by another contributor here -> #34. Please have a look at the latest version **v1.4.0**.
https://github.com/marketplace/actions/dotnet-test-reporter
Your API file had no tests so it was missing one of the xml nodes. Now there is a null check to prevent this kind of issues.
On an unrelated note your coverage file does not correspond to opencover format so it wont show any coverage

**Comment by bibipkins** [comment]
@brunosmm Sorry for taking so long to respond! If you are still interested bug with trx parsing has already been reported and fixed by another contributor here -> https://github.com/bibipkins/dotnet-test-reporter/pull/34. Please have a look at the latest version v1.4.0.
https://github.com/marketplace/actions/dotnet-test-reporter
Your API file had no tests so it was missing one of the xml nodes. Now there is a null check to prevent this kind of issues.
On an unrelated note your coverage file does not correspond to opencover format so it wont show any coverage

**Comment by brunosmm** [comment]
Thanks for the update! I will give a try
